global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "traefik"
    static_configs:
      - targets: ["traefik:8080"]

  - job_name: "sinesys_app"
    dns_sd_configs:
      - names:
          - "tasks.sinesys_app"
        type: "A"
        port: 3000
